// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalAPI.Data;

#nullable disable

namespace MinimalAPI.Migrations
{
    [DbContext(typeof(SQLiteDbContext))]
    partial class SQLiteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("MinimalAPI.Entities.RuleCarProduction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SequenceDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalProduction")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RuleCarProductions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DayName = "Senin",
                            Priority = 2,
                            SequenceDay = 1,
                            TotalProduction = 4
                        },
                        new
                        {
                            Id = 2,
                            DayName = "Selasa",
                            Priority = 1,
                            SequenceDay = 2,
                            TotalProduction = 5
                        },
                        new
                        {
                            Id = 3,
                            DayName = "Rabu",
                            Priority = 2,
                            SequenceDay = 3,
                            TotalProduction = 1
                        },
                        new
                        {
                            Id = 4,
                            DayName = "Kamis",
                            Priority = 1,
                            SequenceDay = 4,
                            TotalProduction = 7
                        },
                        new
                        {
                            Id = 5,
                            DayName = "Jumat",
                            Priority = 1,
                            SequenceDay = 5,
                            TotalProduction = 6
                        },
                        new
                        {
                            Id = 6,
                            DayName = "Sabtu",
                            Priority = 2,
                            SequenceDay = 6,
                            TotalProduction = 4
                        },
                        new
                        {
                            Id = 7,
                            DayName = "Minggu",
                            Priority = 0,
                            SequenceDay = 7,
                            TotalProduction = 0
                        });
                });

            modelBuilder.Entity("MinimalAPI.Entities.TransactionCarProduction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Jumat")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kamis")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Minggu")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rabu")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sabtu")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Selasa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Senin")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TransactionCarProductions");
                });
#pragma warning restore 612, 618
        }
    }
}
